// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example Usage:
/// ```dart
/// import 'firebase_options.dart';
/// // Initialize Firebase with platform-specific options
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Retrieves platform-specific Firebase configuration
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Return Firebase configuration for Web
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android; // Return Firebase configuration for Android
      case TargetPlatform.iOS:
        return ios; // Return Firebase configuration for iOS
      case TargetPlatform.macOS:
        return macos; // Return Firebase configuration for macOS
      case TargetPlatform.windows:
        return windows; // Return Firebase configuration for Windows
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        ); // Unsupported platform error
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        ); // Unsupported platform error
    }
  }

  /// Firebase configuration for Web
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIxuHqdJHGRzv1hgBj1appsRw0BMqxrOU',
    appId: '1:232165675797:web:13326712f20f745dc10f1c',
    messagingSenderId: '232165675797',
    projectId: 'isl-kids-app-e5e12',
    authDomain: 'isl-kids-app-e5e12.firebaseapp.com',
    storageBucket: 'isl-kids-app-e5e12.firebasestorage.app',
    measurementId: 'G-6MQMFYR75W',
  );

  /// Firebase configuration for Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8eb0S5N1Ozfc0cGz_DcS2izYoohmlEQk',
    appId: '1:232165675797:android:986a8e0260ba6f38c10f1c',
    messagingSenderId: '232165675797',
    projectId: 'isl-kids-app-e5e12',
    storageBucket: 'isl-kids-app-e5e12.firebasestorage.app',
  );

  /// Firebase configuration for iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbbnf4beIVk14K30gjLmtodAYRC7nwwlM',
    appId: '1:232165675797:ios:db5741fab40892b3c10f1c',
    messagingSenderId: '232165675797',
    projectId: 'isl-kids-app-e5e12',
    storageBucket: 'isl-kids-app-e5e12.firebasestorage.app',
    iosBundleId: 'com.example.islKidsApp',
  );

  /// Firebase configuration for macOS
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbbnf4beIVk14K30gjLmtodAYRC7nwwlM',
    appId: '1:232165675797:ios:db5741fab40892b3c10f1c',
    messagingSenderId: '232165675797',
    projectId: 'isl-kids-app-e5e12',
    storageBucket: 'isl-kids-app-e5e12.firebasestorage.app',
    iosBundleId: 'com.example.islKidsApp',
  );

  /// Firebase configuration for Windows
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIxuHqdJHGRzv1hgBj1appsRw0BMqxrOU',
    appId: '1:232165675797:web:b73eb69e8cd0f5cbc10f1c',
    messagingSenderId: '232165675797',
    projectId: 'isl-kids-app-e5e12',
    authDomain: 'isl-kids-app-e5e12.firebaseapp.com',
    storageBucket: 'isl-kids-app-e5e12.firebasestorage.app',
    measurementId: 'G-YM8L0BPE0T',
  );
}
